development: &local
  email:
    sender: noreply@mightbuy.it
  facebook:
    appid: "453848267979693"
    token: d98f7e515ae042d5241b4799cfe4d9c1

  twitter:
    appid: kLGDHfctWCOTax3IY0Nwig
    token: vP2xNwMj4jpntS6qN8Z37fY1qUTSk1vDgJT8b1HSs

test:
  <<: *local

production:
  <<: *local
  facebook:
    appid: "461844450500925"
    token: 4c9659082e85db5f8e0b8db4122060e9

  twitter:
    appid: kLGDHfctWCOTax3IY0Nwig
    token: vP2xNwMj4jpntS6qN8Z37fY1qUTSk1vDgJT8b1HSs
