development: &local
  email:
    sender: noreply@mightbuy.it
  facebook:
    appid: "361205880625409"
    token: 6ee39bb339038cc00fee44c336f4b029
    og:
      namespace: testmightbuyit
      action: review
      object: topic

  twitter:
    appid: kLGDHfctWCOTax3IY0Nwig
    token: vP2xNwMj4jpntS6qN8Z37fY1qUTSk1vDgJT8b1HSs
  app_url: "http://mightbuy.dev"

test:
  <<: *local

production:
  <<: *local
  facebook:
    appid: "461844450500925"
    token: 4c9659082e85db5f8e0b8db4122060e9
    og:
      namespace: mightbuy-staging
      action: review
      object: item

  twitter:
    appid: kLGDHfctWCOTax3IY0Nwig
    token: vP2xNwMj4jpntS6qN8Z37fY1qUTSk1vDgJT8b1HSs
  app_url: "https://www.mightbuy.it"
